import {
  Box,
  Button,
  Divider,
  Flex,
  FormControl,
  Grid,
  Heading,
  Icon,
  Img,
  Input,
  Select,
  Stack,
  Text,
  useColorMode,
} from '@chakra-ui/react';
import Head from 'next/head';
import React from 'react';
import { FaRegClock, FaCircle, FaPlayCircle, FaFacebook } from 'react-icons/fa';
import { ChevronLeftIcon, ChevronRightIcon } from '@chakra-ui/icons';
import Videoslider from '../component/slider/Video';
import Link from 'next/link';

import Home from '../component/Home';

const Index = () => {
  // theming
  const { colorMode, toggleColorMode } = useColorMode();
  const isLightTheme = colorMode == 'light' ? true : false;
  const primaryTextColor = isLightTheme ? 'black' : 'white';
  const secondaryTextColor = isLightTheme ? 'white' : 'black';
  const primaryBgColor = isLightTheme ? 'white' : 'black';
  const secondaryBgColor = isLightTheme ? 'black' : 'white';

  //  varibles

  return (
    <>
      {/* <Head>
        <title>Meta-Desk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Head>
        <title data-rh="true">News Control - get the latest news</title>
        <meta
          name="description"
          content="Get the latest news for Bollywood, IPL, Sports and Other Social breaking news"
        />

        <link rel="canonical" href="https://newsctrls.com/" />
      </Head>

      <Home />
    </>
  );
};

export default Index;
